homepage:
    path: /
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: 'homepage.html.twig'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
