homepage:
    path: /
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: 'homepage.html.twig'

_ui_index:
    path: /_ui/index
    methods: [GET]
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
        template: 'ui/index.html.twig'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
